baseURL: "https://beyondf1.netlify.app/"
languageCode: "en-us"
title: "BeyondF1"
enableRobotsTXT: true

params:
  author: Spectral Jager
  description: Your guide from The Ocean of empty talks to The Island of meaning. 
  googleAnalyticsID: "G-P3B90SMZ6J"
  links:
    - name: Twitter
      link: https://twitter.com/SpectrumUnkn
      username: SpectrumUnkn
      icon: <i class="bi bi-twitter"></i>
    - name: GitHub
      link: https://github.com/SpectralJager
      username: SpectralJager
      icon: <i class="bi bi-github"></i>
    - name: LinkedIn
      link: https://www.linkedin.com/in/spectraljager
      username: spectraljager
      icon: <i class="bi bi-linkedin"></i>

paginate: 4

menu:
  main:
    - name: <i class="bi bi-stickies me-2"></i> posts
      url: "/posts"
      weight: 1
    
    
taxonomies:
  category: categories
  tag: tags